server:
  port: 6060
  servlet:
    context-path: /json-data-creator

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/?maxPoolSize=20&w=majority
      database: JSON_MODEL_DATABASE
      auto-index-creation: true
      port: 27017
      host: 127.0.0.1
      username: admin
      password: admin
         
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /api-docs    
     